- name: install python-mysqldb
  apt:
    name: python-mysqldb
    state: latest
    force: yes

- name: modify ~/.my.cnf
  template:
    src: mysql/my.cnf
    dest: ~/.my.cnf
    mode: 0600
  when: "zabbix_mysql_host != 'localhost'"

- name: modify mysql user
  mysql_user:
    host: "{{ zabbix_mysql_host }}"
    name: "{{ zabbix_mysql_user }}"
    password: "{{ zabbix_mysql_password }}"
    priv: "{{ zabbix_mysql_database }}.*:ALL"
    state: present

- name: modify mysql database
  mysql_db:
    login_host: "{{ zabbix_mysql_host }}"
    name: "{{ zabbix_mysql_database }}"
    state: present
  register: create_zabbix_database

- name: modify mysql database schema
  mysql_db:
    login_host: "{{ zabbix_mysql_host }}"
    login_user: "{{ zabbix_mysql_user }}"
    login_password: "{{ zabbix_mysql_password }}"
    name: "{{ zabbix_mysql_database }}"
    state: import
    target: "/usr/local/src/zabbix-{{ zabbix_version }}/database/mysql/{{ item }}"
  with_items:
    - schema.sql
    - images.sql
    - data.sql
  when: create_zabbix_database|changed
