- name: modify nginx config
  template:
    src: nginx/zabbix.conf
    dest: /etc/nginx/conf.d/zabbix.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: modify zabbix frontend
  command: "{{ item }}"
  args:
    creates: /usr/local/sbin/zabbix_server/index.php
  with_items:
    - "cp -prf /usr/local/src/zabbix-{{ zabbix_version }}/frontends/php /usr/share/nginx/zabbix"
    - "chown nginx:nginx -R /usr/share/nginx/zabbix"
