- name: modify nginx config
  template:
    src: nginx/zabbix.conf
    dest: /etc/nginx/conf.d/zabbix.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: copy zabbix frontend source
  command: "cp -prf /usr/local/src/zabbix-{{ zabbix_version }}/frontends/php /usr/share/nginx/zabbix"
  args:
    creates: /usr/share/nginx/zabbix

- name: modify zabbix frontend directory
  file:
    path: /usr/share/nginx/zabbix
    state: directory
    owner: nginx
    group: nginx
    recurse: yes
